const data_aze = [

{  },
{   },
{  "meaning_aze": "Ruzi verən" },
{ "aze": "Əl-Fəttah", "meaning_aze": "Açıcı. Çətinlikləri həll edən" },
{ "aze": "Əl-Aliim", "meaning_aze": "Hər şeyi bilən. Çox Elmli" },
{ "aze": "Əl-Qabid", "meaning_aze": "Daraldan" },
{ "aze": "Əl-Basit", "meaning_aze": "Böyüdücü" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əs-Səmi", "meaning_aze": "Hər şeyi eşidən" },
{ "aze": "Əl-Bəsir", "meaning_aze": "Hər şeyi görən (haqq-nahaqq)" },
{ "aze": "Əl-Hakam", "meaning_aze": "Hakim" },
{ "aze": "Əl-Ədl", "meaning_aze": "Ədalətli" },
{ "aze": "Əl-Lətif", "meaning_aze": "İşlərin incəliklərini bilən" },
{ "aze": "Əl-Xabir", "meaning_aze": "Məlumatlı" },
{ "aze": "Əl-Həlim", "meaning_aze": "Çox Mülayim" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əl-Ğafur", "meaning_aze": "Günahları Bağışlayan" },
{ "aze": "Əş-Şəkur", "meaning_aze": "Mükafatlandıran" },
{ "aze": "Əl-Ali", "meaning_aze": "Uca" },
{ "aze": "Əl-Kəbir", "meaning_aze": "Ən böyük" },
{ "aze": "Əl-Hafiz", "meaning_aze": "Qoruyan. Mühafizəçi" },
{ "aze": "Əl-Muqit", "meaning_aze": "Ruzi verən. Təmin edən" },
{ "aze": "Əl-Hasib", "meaning_aze": "Hər şeyi hesaba alan" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əl-Kərim", "meaning_aze": "Səxavətli" },
{ "aze": "Ər-Raqib", "meaning_aze": "Nəzarətçi. Keşikçi" },
{ "aze": "Əl-Mucib", "meaning_aze": "Duaları qəbul edən. Cavab verən" },
{ "aze": "Əl-Vəsi", "meaning_aze": "Hərtərəfli" },
{ "aze": "Əl-Hakim", "meaning_aze": "Müdrik. Çox Hikmətli" },
{ "aze": "Əl-Vədud", "meaning_aze": "Ən Çox Sevən" },
{ "aze": "Əl-Məcid", "meaning_aze": "Şanlı" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əş-Şahid", "meaning_aze": "Hər şeyə şahid və nəzarətçi olan" },
{ "aze": "Əl-Haqq", "meaning_aze": "Həqiqi" },
{ "aze": "Əl-Vəkil", "meaning_aze": "Himayəçi" },
{ "aze": "Əl-Qavi", "meaning_aze": "Güc sahibi" },
{ "aze": "Əl-Mətin", "meaning_aze": "Sarsılmaz" },
{ "aze": "Əl-Vəli", "meaning_aze": "Himayəçi" },
{ "aze": "Əl-Həmid", "meaning_aze": "Təqdirəlayiq. Həmd edilən" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əl-Muhyi", "meaning_aze": "Dirildən. Həyat verən" },
{ "aze": "Əl-Mumit", "meaning_aze": "Öldürən" },
{ "aze": "Əl-Hayy", "meaning_aze": "Daima diri olan" },
{ "aze": "Əl-Qəyyum", "meaning_aze": "Müstəqil" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əl-Vahid", "meaning_aze": "Tək olan. Yeganə" },
{ "aze": "Əl-Əhəd", "meaning_aze": "Bənzərsiz" },
{ "aze": "Əs-Saməd", "meaning_aze": "Heç kəsə və heç nəyə ehtiyacı olmayan" },
{ "aze": "Əl-Qadiir", "meaning_aze": "Qüdrətli" },
{ "aze": "Əl-Müqtədir", "meaning_aze": "İqtidarlı" },
{ "aze": "Əl-Müqaddim", "meaning_aze": "Əvvələ çəkən" },
{ "aze": "Əl-Muəxxir", "meaning_aze": "Təxirə salan" },
{ "aze": "Əl-Əvvəl", "meaning_aze": "Hər şeydən əvvəl mövcud olmuş" },
{ "aze": "Əl-Axir", "meaning_aze": "Hər şeydən sonda mövcud olan" },
{ "aze": "Əz-Zahir", "meaning_aze": "Aşkarda olan (aşkardakıları bilən)" },
{ "aze": "Əl-Batin", "meaning_aze": "Gizlində olan (gizlindəkiləri bilən)" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əl-Mütəali", "meaning_aze": "Ucaldılmış" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əl-Əfüvv", "meaning_aze": "Əfv edən. Bağışlayan" },
{ "aze": "Ər-Rəuf", "meaning_aze": "Mehriban. Şəfqətli" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Zul-Cəlil vəl-İkram", "meaning_aze": "Əzəmət, Ucalıq və Səxavət Sahibi" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Ən-Nur", "meaning_aze": "Nur" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "Əl-Bədi", "meaning_aze": "Həmişə ixtira edən" },
{ "aze": "Əl-Baqi", "meaning_aze": "Əbədi. Daimi. Qaları" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },
{ "aze": "", "meaning_aze": "" },

{ "aze": "Əl-Qahir", "meaning_aze": "Zalımları qəhr edən" },
{ "aze": "Əl-Alə", "meaning_aze": "Ən Uca. Ən Yüksək" },
{ "aze": "Əl-Əkrəm", "meaning_aze": "Ən Səxavətli. Ən Kəramətli" },
{ "aze": "Ər-Rai", "meaning_aze": "Hər şeyi görən" },
{ "aze": "Əl-Mubin", "meaning_aze": "Aydınlaşdırıcı" },
{ "aze": "Əl-Xalləq", "meaning_aze": "Yaradan" },
{ "aze": "Əş-Şakir", "meaning_aze": "Minnətdar" },
{ "aze": "Əl-Maulə", "meaning_aze": "Sahib" },
{ "aze": "Ən-Nasir", "meaning_aze": "Köməkçi" },
{ "aze": "Əl-Qarib", "meaning_aze": "Yaxın olan" },
{ "aze": "Ər-Rəbb", "meaning_aze": "Hökmdar. Bəsləyən" },
{ "aze": "Əl-Qadir", "meaning_aze": "Qüdrətli" },
{ "aze": "Əl-Kafi", "meaning_aze": "Kifayət edən" },
{ "aze": "Əs-Sittir", "meaning_aze": "Gizlədən" },
{ "aze": "Əl-İlah", "meaning_aze": "İlahi" },
{ "aze": "Əl-Qədir", "meaning_aze": "Hər şeyə qüdrəti çatan" },
{ "aze": "Əl-Əliyy", "meaning_aze": "Yüksək. Uca" },
{ "aze": "Əl-Həfiyy", "meaning_aze": "Öz yaratdıqlarını çox sevən" }
];

export { data_aze };