const data_aze = [
{ "aze": "Ər-Rəhman", "meaning": "Çox Mərhəmətli" },
{ "aze": "Ər-Rəhim", "meaning": "Həmişə Mərhəmətli. Rəhimli" },
{ "aze": "Əl-Məlik", "meaning": "Ali hökmdar" },
{ "aze": "Əl-Qüddus", "meaning": "Müqəddəs" },
{ "aze": "Əs-Salam", "meaning": "Pak. Əmin-amanlıq verən" },
{ "aze": "Əl-Mömin", "meaning": "İman bəxş edən (İman bəslənilən)" },
{ "aze": "Əl-Mühəymin", "meaning": "Mühafizəçi. Himayə edən" },
{ "aze": "Əl-Əziz", "meaning": "Əzəmətli. Çox İzzətli" },
{ "aze": "Əl-Cabbar", "meaning": "Qüdrətli. Zalımlara əziyyət verən" },
{ "aze": "Əl-Mütəkəbbir", "meaning": "Məqamı uca tutulan, böyüdülən" },
{ "aze": "Əl-Xaliq", "meaning": "Yaradıcı" },
{ "aze": "Əl-Bari", "meaning": "Heçdən yaradan" },
{ "aze": "Əl-Müsavvir", "meaning": "Surət verən" },
{ "aze": "Əl-Qaffar", "meaning": "Hər şeyi bağışlayan" },
{ "aze": "Əl-Qahhar", "meaning": "Hakimi-mütləq" },
{ "aze": "Əl-Vahhab", "meaning": "Səxavətli" },
{ "aze": "Ər-Razzaq", "meaning": "Ruzi verən" },
{ "aze": "Əl-Fəttah", "meaning": "Açıcı. Çətinlikləri həll edən" },
{ "aze": "Əl-Aliim", "meaning": "Hər şeyi bilən. Çox Elmli" },
{ "aze": "Əl-Qabid", "meaning": "Daraldan" },
{ "aze": "Əl-Basit", "meaning": "Böyüdücü" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "Əs-Səmi", "meaning": "Hər şeyi eşidən" },
{ "aze": "Əl-Bəsir", "meaning": "Hər şeyi görən (haqq-nahaqq)" },
{ "aze": "Əl-Hakam", "meaning": "Hakim" },
{ "aze": "Əl-Ədl", "meaning": "Ədalətli" },
{ "aze": "Əl-Lətif", "meaning": "İşlərin incəliklərini bilən" },
{ "aze": "Əl-Xabir", "meaning": "Məlumatlı" },
{ "aze": "Əl-Həlim", "meaning": "Çox Mülayim" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Ğafur", "meaning": "Günahları Bağışlayan" },
{ "aze": "Əş-Şəkur", "meaning": "Mükafatlandıran" },
{ "aze": "Əl-Ali", "meaning": "Uca" },
{ "aze": "Əl-Kəbir", "meaning": "Ən böyük" },
{ "aze": "Əl-Hafiz", "meaning": "Qoruyan. Mühafizəçi" },
{ "aze": "Əl-Mühit", "meaning": "Hər şeyi qavrayan" },
{ "aze": "Əl-Hasib", "meaning": "Hər şeyi hesaba alan" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Kərim", "meaning": "Səxavətli" },
{ "aze": "Ər-Raqib", "meaning": "Nəzarətçi. Keşikçi" },
{ "aze": "Əl-Mucib", "meaning": "Duaları qəbul edən" },
{ "aze": "Əl-Vəsi", "meaning": "Hərtərəfli" },
{ "aze": "Əl-Hakim", "meaning": "Müdrik. Çox Hikmətli" },
{ "aze": "Əl-Vədud", "meaning": "Ən Çox Sevən" },
{ "aze": "Əl-Məcid", "meaning": "Şanlı" },
{ "aze": "", "meaning": "" },
{ "aze": "Əş-Şahid", "meaning": "Hər şeyə şahid və nəzarətçi olan" },
{ "aze": "Əl-Haqq", "meaning": "Həqiqi" },
{ "aze": "Əl-Vəkil", "meaning": "Himayəçi" },
{ "aze": "Əl-Qavi", "meaning": "Güc sahibi" },
{ "aze": "Əl-Mətin", "meaning": "Sarsılmaz" },
{ "aze": "Əl-Vəli", "meaning": "Himayəçi" },
{ "aze": "Əl-Həmid", "meaning": "Təqdirəlayiq. Həmd edilən" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Hayy", "meaning": "Daima diri olan" },
{ "aze": "Əl-Qəyyum", "meaning": "Müstəqil" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Vahid", "meaning": "Tək olan. Yeganə" },
{ "aze": "Əl-Əhəd", "meaning": "Bənzərsiz" },
{ "aze": "Əs-Səməd", "meaning": "Ehtiyacsız" },
{ "aze": "Əl-Qadiir", "meaning": "Qüdrətli" },
{ "aze": "Əl-Müqtədir", "meaning": "İqtidarlı" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Əvvəl", "meaning": "Hər şeydən əvvəl mövcud olmuş" },
{ "aze": "Əl-Axir", "meaning": "Hər şeydən sonda mövcud olan" },
{ "aze": "Əz-Zahir", "meaning": "Aşkarda olan (aşkardakıları bilən)" },
{ "aze": "Əl-Batin", "meaning": "Gizlində olan (gizlindəkiləri bilən)" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Mütəali", "meaning": "Ucaldılmış" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Əfüvv", "meaning": "Əfv edən. Bağışlayan" },
{ "aze": "Ər-Rəuf", "meaning": "Mehriban. Şəfqətli" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "Ən-Nur", "meaning": "Nur" },
{ "aze": "", "meaning": "" },
{ "aze": "Əl-Bədi", "meaning": "Həmişə ixtira edən" },
{ "aze": "Əl-Baqi", "meaning": "Əbədi. Daimi. Qaları" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },
{ "aze": "", "meaning": "" },

{ "aze": "Əl-Qahir", "meaning": "Zalımları qəhr edən" },
{ "aze": "Əl-Alə", "meaning": "Ən Uca. Ən Yüksək" },
{ "aze": "Əl-Əkrəm", "meaning": "Ən Səxavətli. Ən Kəramətli" },
{ "aze": "Ər-Rai", "meaning": "Hər şeyi görən" },
{ "aze": "Əl-Mubin", "meaning": "Aydınlaşdırıcı" },
{ "aze": "Əl-Xalləq", "meaning": "Yaradan" },
{ "aze": "Əş-Şakir", "meaning": "Minnətdar" },
{ "aze": "Əl-Maulə", "meaning": "Sahib" },
{ "aze": "Ən-Nasir", "meaning": "Köməkçi" },
{ "aze": "Əl-Qarib", "meaning": "Yaxın olan" },
{ "aze": "Ər-Rəbb", "meaning": "Hökmdar. Bəsləyən" },
{ "aze": "Əl-Qadir", "meaning": "Qüdrətli" },
{ "aze": "Əl-Kafi", "meaning": "Kifayət edən" },
{ "aze": "Əs-Sittir", "meaning": "Gizlədən" },
{ "aze": "Əl-İlah", "meaning": "İlahi" },
{ "aze": "Əl-Qədir", "meaning": "Hər şeyə qüdrəti çatan" },
{ "aze": "Əl-Əliyy", "meaning": "Yüksək. Uca" },
{ "aze": "Əl-Həfiyy", "meaning": "Öz yaratdıqlarını çox sevən" }
];

export { data_aze };